### ISSUE TITLE
Game Crash When Running with BetterWithMods and Immersive Engineering

### ISSUE THREAD

**Issue by SpectrumR2** [AquUpd/LeftHambldMod#2]
All versions of Custom-Hands-GUI for MC 1.12.2 cause Minecraft to fail to launch when Immersive Engineering and BetterWithMods are installed. 
The issue does not occur if Custom-Hands-GUI is installed with only Immersive Engineering or only BetterWithMods.

Both Immserive Engineering and BetterWithMods need to be installed to cause this crash.

I am submitting a crash report from an installation where only Custom Hands GUI, Immersive Engineering, and BetterWithMods are installed.

I posted a report on BetterWithMods' tracker as well. I tried to do so for Immersive Engineering but support for 1.12.2 has already ended.

I'd love to use this mod in a modpack I am playing. So if there is any way to resolve this then I would be extremely grateful.

Thank You,
Carson B.

Crash Report: https://pastebin.com/LaSRSC48

**Comment by Ivan-Khar** [comment]
Weird thing, thanks! I'll try to fix it

**Comment by Ivan-Khar** [comment]
For now you can disable ImmersiveEngineering compatibility module in "betterwithmods.cfg" file

**Comment by Ivan-Khar** [comment]
I think it only makes Hemp seeds not drop from grass blocks

**Comment by SpectrumR2** [comment]
Great advice! I'm no longer crashing with your mod now. I really appreciate
your quick response time, that's stellar!

Thank you again,
Carson B.

**Comment by Ivan-Khar** [comment]
I'll close it for now
